### ISSUE TITLE
В теглайн проекта добавь "OSM" или "OpenSteetMap"

### ISSUE THREAD

**Issue by d1g** [kiselev-dv/gazetteer#35]
Иначе не находит совсем https://github.com/search?utf8=%E2%9C%93&q=osm+geocoder&type=Repositories

Вот этот находит: https://github.com/chatman/osm-geocoder

**Comment by kiselev-dv** [comment]
Вообще osm в ридмишке был упомянут. Не знаю с какой скоростью гитхаб ридмишки реиндексирует. Посмотрим что будет через пару дней находить.

**Comment by d1g** [comment]
Как я понял, там нужно не readme, а в теглайн проекта добавлять (сейчас он пустой), а то не найдёт 

https://github.com/MarcusWolschon/osmeditor4android/issues/333#issuecomment-135937593

**Comment by kiselev-dv** [comment]
Готово
