### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by arcusfelis** [kiselev-dv/gazetteer#36]
```erlang
mvn clean compile assembly:single -f Gazetteer/pom.xml
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Gazetteer 1.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for me.osm.osm-doc:osm-doc-java:jar:0.11 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.868s
[INFO] Finished at: Sat Sep 19 02:34:41 CEST 2015
[INFO] Final Memory: 6M/236M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Gazetteer: Could not resolve dependencies for project me.osm.Gazetteer:Gazetteer:jar:1.4-SNAPSHOT: Failure to find me.osm.osm-doc:osm-doc-java:jar:0.11 in http://raw.githubusercontent.com/kiselev-dv/mvn-repository/master/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of osm-doc-mvn-repo has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by kiselev-dv** [comment]
Have you  done 

    # Install kiselev-dv/osm-doc-java
    mvn compile install -f osm-doc-java/pom.xml

before?

**Comment by ricadete** [comment]
Good afternoon,

I also have the same issue. Any idea what to do? I followed these steps:

# Install kiselev-dv/osm-doc-java
mvn compile install -f osm-doc-java/pom.xml

# Install kiselev-dv/ExternalSorting
# It was forked, so test will fails
mvn -Dmaven.test.skip=true compile install -f ExternalSorting/pom.xml

# Compile and assemble gazetteer
mvn clean compile assembly:single -f Gazetteer/pom.xml

Thanks in advance.

**Comment by kiselev-dv** [comment]
Could you give me maven logs for 

    mvn compile install -f osm-doc-java/pom.xml
    mvn -Dmaven.test.skip=true compile install -f ExternalSorting/pom.xml
    mvn clean compile assembly:single -f Gazetteer/pom.xml

**Comment by ricadete** [comment]
Thanks for helping.
Here it is:

[kiselev.txt](https://github.com/kiselev-dv/gazetteer/files/37619/kiselev.txt)

**Comment by kiselev-dv** [comment]
The problem is:
Current branch of osm-doc-java is `1.0-SNAPSHOT` but Gazetteer looking for `osm-doc-java 0.11`

I added public repository and hope it will be much more easier to use.
You could use latest version `1.5-SNAPSHOT`
or you could checkout `Gazetteer-1.4` and edit pom.xml add

    <repository>
	    <id>myMavenRepo.read</id>
	    <url>https://mymavenrepo.com/repo/rRfVAWWQw6RiXxhmZkot/</url>
	    <snapshots>
		    <enabled>true</enabled>
		    <updatePolicy>always</updatePolicy>
	    </snapshots>
    </repository>

to `<repositories>` section

**Comment by ricadete** [comment]
Yes, that solved! Thank you a lot!
