### ISSUE TITLE
split and slice succeed,but block at join using Gazetteer-1.3

### ISSUE THREAD

**Issue by burningc** [kiselev-dv/gazetteer#38]
the output file is 10 bytes and join doesn't finish.
command:
java -jar gazetteer.jar split map.osm
java -jar gazetteer.jar slice
java -jar gazetteer.jar join --handlers out-gazetteer ./out.json.gz

**Comment by kiselev-dv** [comment]
How big is map.osm

**Comment by burningc** [comment]
No matter how bit the map is(from dozens of kb to hundreds of MB),it always blocks at the last join step.I download maps from https://mapzen.com/data/metro-extracts.

**Comment by kiselev-dv** [comment]
Try. v1.4 I've succeeded with Beijing for instance. 
Try 
    
    java -jar gazetteer.jar slice --x10
    java -Xmx2g -jar gazetteer.jar --threads 2 join --handlers out-gazetteer ./out.json.gz

**Comment by burningc** [comment]
v1.4 works.Thank you for your great work!

**Comment by kiselev-dv** [comment]
Glad to hear that. Also keep an eye on https://github.com/kiselev-dv/gazetteer/issues/39 it's rather close issue.
