### ISSUE TITLE
add osm node ids to Gazetteer objects

### ISSUE THREAD

**Issue by cordovapolymer** [kiselev-dv/gazetteer#46]
Please add osm node ids to Gazetteer objects, currently "id" key starts with tag name and osm node id is somewhere in the middle, so is very difficult to parse. 
It would be great to have structured osm id object with osm node or way id, type and tag, for ex. `{'id': '25496583', 'type': 'node', 'highway': 'traffic_signals'}` or `{'id': '25496583', 'type': 'way', 'highway': 'motorway'}`

**Comment by cordovapolymer** [comment]
any hope that it will be fixed?

**Comment by kiselev-dv** [comment]
Yes, I'll take a look if you still need that.

**Comment by cordovapolymer** [comment]
will be awesome!

**Comment by cordovapolymer** [comment]
@kiselev-dv do you have an update on this? )
