### ISSUE TITLE
Output to CSV - Syntax

### ISSUE THREAD

**Issue by linuzer** [kiselev-dv/gazetteer#49]
Hi,

while working with the gazetteer (btw. great tool!) to extract addresses from OSM I found in the Readme the note, that it is possible to output also to CSV-format. Unfortunately I was not able to figure out how to do this. Could you give me please a little example?

Thanks a lot!

**Comment by kiselev-dv** [comment]
This is the basic example, it shows how to encode columns for csv handler:

`--handlers out-csv out=file.csv.gz columns=osm-id,id`

But it says nothing about columns itself. You can find column keys here: 

* https://github.com/kiselev-dv/gazetteer/blob/develop/Gazetteer/src/main/java/me/osm/gazetter/out/FeatureValueExctractorImpl.java
* https://github.com/kiselev-dv/gazetteer/blob/develop/Gazetteer/src/main/java/me/osm/gazetter/out/AddrRowValueExctractorImpl.java

The difference between `AddrRowValueExctractorImpl` and `FeatureValueExctractorImpl` is that one feature (building or poi or whatewer) may have more than one address. Columns in `FeatureValueExctractorImpl` are for the whole feature and `AddrRowValueExctractorImpl` for each address inside feature.

If feature contains more than one address, lets say 2 addresses, the output csv will has 2 rows, data from `FeatureValueExctractorImpl` will be the same, and data from `AddrRowValueExctractorImpl` will be specific.

Sorry for very late answer.

**Comment by kiselev-dv** [comment]
https://github.com/kiselev-dv/gazetteer/wiki/csv-output
