### ISSUE TITLE
Extract only addresses?

### ISSUE THREAD

**Issue by linuzer** [kiselev-dv/gazetteer#50]
Another question I have: Is it possible to extract only addresses, and no highways or other data?

Thanks a lot!

**Comment by kiselev-dv** [comment]
Yo can ignore them in output file, but the only type which can be thrown away is poi. To do that use `slice all,no-poi` 

If you'll skip highways duiring slice, all the highways related data will be missed in final data-set.

**Comment by linuzer** [comment]
Thanks for the help!
